swagger: "2.0"
info:
  description: "Description of the CAMI Event Insertion API."
  version: "1.0.0"
  title: "CAMI Event Insertion Endpoint"
  termsOfService: "http://swagger.io/terms/"

host: 141.85.241.224
basePath: "/api/v1/insertion"
tags:
- name: "events"
  description: "Event insertion endpoint" 
schemes:
- "http"
paths:
  /events:
    post:
      tags:
      - "events"
      summary: "Insert a new event into the CAMI Cloud Event Stream Manager"
      description: ""
      operationId: "insertEvent"
      consumes:
      - "application/json"
      - "application/rdf"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Event object that needs to be inserted in the CAMI Cloud Event Stream Manager"
        required: true
        schema:
          $ref: "#/definitions/Event"
      responses:
        201:
          description: "Event successfully inserted"
        405:
          description: "Invalid event content"

definitions:
  Event:
    type: "object"
    properties:
      category: 
        type: "string"
        description: "The category in which this event is classified. An event can relate to the home environment, the user's health or his response to notifications generated by the CAMI system."
        enum:
          - USER_ENVIRONMENT
          - USER_HEALTH
          - USER_NOTIFICATIONS
      
      content:
        $ref: "#/definitions/EventContent"
      
      annotations:
        $ref: "#/definitions/EventAnnotations"
  
  EventContent:
    type: "object"
    properties:
      name: 
        type: "string"
        description: "Name of the event generated. It is left general, but it will essentially be a big enumeration of event types."
        example: "presence_detected | kitchen_window"
      value_type:
        type: "string"
        description: "The value type of the event content. The content may be of numeric form, strings (including enumerations), boolean values or a complex structure. The latter is an additional object that identifies all the entities that take part in the event."
        enum:
          - integer
          - float
          - string
          - enum
          - boolean
          - complex
      value:
        type: "string"
        description: "The value of the event content. In case of a complex type, the value will be a JSON description of the entities involved in the event. For example in an event of type presence_detected, the entities can be the user who is detected and the room where he is detected. The room is identified just by its name, while the user is described using his name and the URL of the corresponding user resource."
        example:
          user:
            name: "Jim"
            uri: "/v1/resources/user/1/"
          room:
            name: "Kitchen"
      
  EventAnnotations:
    type: "object"
    description: "Meta properties of the inserted event."
    required:
      - timestamp
    properties:
      timestamp:
        type: "integer"
        format: "int64"
        description: "The time at which this event was detected/generated, given as a Unix Epoch timestamp."
      source:
        type: "string"
        description: "The source of this event. This will either be the URI of a device/sensor if the device is stored in the CAMI Store or the keyword 'DSS', if the event is inferred by the CAMI Decision Support Service."
        example: 
          - "DSS | /v1/resources/devices/3/"
      certainty:
        type: "number"
        description: "Degree of certainty in the provided event."
      temporal_validity:
        $ref: "#/definitions/ValidityInterval"
  
  ValidityInterval:
    type: "object"
    description: "The time interval during which the asserted event is considered to be / have been valid."
    properties:
      start_ts: 
        type: "integer"
        format: "int64"
        description: "The start of the validity interval, given as UNIX Epoch timestamp."
      end_ts: 
        type: "integer"
        format: "int64"
        description: "The end of the validity interval, given as UNIX Epoch timestamp."
      