swagger: "2.0"
info:
  description: "Description of the CAMI Event Insertion API."
  version: "1.0.0"
  title: "CAMI Health Measurement Insertion Endpoint"
  termsOfService: "http://swagger.io/terms/"

host: 141.85.241.224
basePath: "/api/v1/insertion"
tags:
- name: "measurements"
  description: "CAMI health measurement insertion endpoint" 
schemes:
- "http"
paths:
  /measurements:
    post:
      tags:
      - "measurements"
      summary: "Insert a new health measurement into the CAMI Cloud Event Stream Manager"
      operationId: "insertMeasurement"
      consumes:
      - "application/json"
      - "application/rdf"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Measurement object that needs to be inserted in the CAMI Cloud Event Stream Manager"
        required: true
        schema:
          $ref: "#/definitions/Measurement"
      responses:
        201:
          description: "Measurement successfully inserted"
        405:
          description: "Invalid measurement content"

definitions:
  Measurement:
    type: "object"
    required:
    - "measurement_type"
    - "unit_type"
    - "timestamp"
    - "user"
    - "device"
    - "value_info"
    properties:
      measurement_type:
        type: "string"
        enum:
          - weight
          - blood_pressure
          - pulse
          - temperature
          - saturation
          - steps
        description: "The type of health measurement that was carried out."
        
      unit_type:
        type: "string"
        enum:
          - kg
          - mmhg
          - bpm
          - celsius
          - no_dim
        description: "The unit of measurement for the recorded health reading."
          
      timestamp:
        type: "integer"
        description: "Time when the measurement was taken, given as UNIX Epoch timestamp."
        format: "int64"
      
      user:
        type: "string"
        description: "The URI corresponding to the User resource present in the CAMI Store, for which this health measurement was taken."
        example: "/api/v1/user/14/"
        format: "URI"
        
      device:
        type: "string"
        description: "The URI corresponding to the Device resource present in the CAMI Store, with which this health measurement was taken."
        example: "/api/v1/device/1/"
        format: "URI"
      
      value_info:
        type: "string"
        description: "A field representing the JSON encoding of the health parameters recorded by this measurement."
        example: "{'systolic': 115, 'diastolic': 70}"
      