# Use a base image that has ansible set up.
FROM williamyeh/ansible:ubuntu16.04

# Add playbooks to the Docker image. This requires that the build context is the
# project root folder.

COPY . /cami-project
WORKDIR /cami-project

# Run Ansible to configure the Docker image
RUN ansible-playbook ansible/store.yml -c local

COPY docker/cami-store/docker-entrypoint.sh /usr/local/bin/
COPY docker/cami-store/docker-migration-entrypoint.sh /usr/local/bin/
COPY docker/cami-store/docker-message-worker-entrypoint.sh /usr/local/bin/
COPY docker/cami-store/docker-message-worker-entrypoint-dev.sh /usr/local/bin/
COPY docker/cami-store/docker-task-scheduler-entrypoint.sh /usr/local/bin/
COPY docker/cami-store/docker-task-scheduler-entrypoint-dev.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-migration-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-message-worker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-message-worker-entrypoint-dev.sh
RUN chmod +x /usr/local/bin/docker-task-scheduler-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-task-scheduler-entrypoint-dev.sh

RUN adduser --disabled-password --gecos '' store
RUN chown -R store /cami-project

USER store

ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 8008