version: '2'
services:
  cami-mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      # Make the MySQL server available on the host so VMs can access it
      - "3307:3306"
  
  cami-store:
    build:
      context: .
      dockerfile: Dockerfile-store
    links:
      - cami-mysql
      - cami-rabbitmq
    ports:
      - "8008:8008"
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-entrypoint.sh

  cami-store-migrate:
    build:
      context: .
      dockerfile: Dockerfile-store
    links:
      - cami-mysql
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-migration-entrypoint.sh

  # Runs the Celery worker for consuming messages received by the store
  cami-store-message-worker:
    build:
      context: .
      dockerfile: Dockerfile-store
    links:
      # Needs the store to interact with the DB
      - cami-mysql
      - cami-rabbitmq
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint-dev.sh

  # Runs the Celery task scheduler for store
  cami-store-task-scheduler:
    build:
      context: .
      dockerfile: Dockerfile-store
    links:
      # Needs the store to interact with the DB
      - cami-mysql
      - cami-rabbitmq
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-task-scheduler-entrypoint-dev.sh

  cami-rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    ports:
      # Make the RabbitMQ server available on the host so VMs can access it
      - "5673:5672"
      - "15673:15672"
  # Run migrations in a separate container from the main applications. The
  # container will just run migrations and load fixtures and then exit.
  cami-medical-compliance-migrate:
    build:
      context: .
      dockerfile: Dockerfile-medical-compliance
    links:
      - cami-mysql
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-migration-entrypoint.sh

  cami-medical-compliance:
    build:
      context: .
      dockerfile: Dockerfile-medical-compliance
    links:
      - cami-mysql
      - cami-rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-entrypoint.sh

  # Runs the Celery worker for consuming messages received by the medical-compliance
  cami-medical-compliance-message-worker:
    build:
      context: .
      dockerfile: Dockerfile-medical-compliance
    links:
      # Needs the store to interact with the DB
      - cami-mysql
      - cami-rabbitmq
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint-dev.sh

  # Runs the Celery task scheduler for medical-compliance
  cami-medical-compliance-task-scheduler:
    build:
      context: .
      dockerfile: Dockerfile-medical-compliance
    links:
      # Needs the store to interact with the DB
      - cami-mysql
      - cami-rabbitmq
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-task-scheduler-entrypoint-dev.sh

  # Run migrations in a separate container from the main applications. The
  # container will just run migrations and load fixtures and then exit.
  cami-frontend-migrate:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    links:
      - cami-mysql
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-migration-entrypoint.sh

  # Should use cached image that is build for cami-frontend-migrate
  cami-frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    links:
      - cami-mysql
      - cami-rabbitmq
    ports:
      - "8001:8001"
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-entrypoint.sh

  # Runs the Celery worker for consuming messages received by the frontend
  cami-frontend-message-worker:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    links:
      # Needs the store to interact with the DB
      - cami-mysql
      - cami-rabbitmq
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint-dev.sh

  # Runs the Celery worker for consuming measurements and distribute them to the Linkwatch platform
  cami-linkwatch-worker:
    build:
      context: .
      dockerfile: Dockerfile-linkwatch
    links:
      # Needs the store to interact with the DB
      - cami-mysql
      - cami-rabbitmq
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint-dev.sh

  # Runs the Celery worker for consuming measurements and distribute them to the OpenTele platform
  cami-opentele-worker:
    build:
      context: .
      dockerfile: Dockerfile-opentele
    links:
      # Needs the store to interact with the DB
      - cami-mysql
      - cami-rabbitmq
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint-dev.sh
