cami-mysql:
  image: vitaminsoftware/cami-project:store
  ports:
    - "3307:3306"
  tty: true
  stdin_open: true
cami-rabbitmq:
  image: vitaminsoftware/cami-project:rabbitmq
  ports:
    - "5673:5672"
    - "15673:15672"
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-store:
  image: vitaminsoftware/cami-project:store
  links:
    - 'cami-mysql'
  ports:
    - "8008:8008"
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-store-migrate:
  image: vitaminsoftware/cami-project:store
  links:
    - 'cami-mysql'
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-migration-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
cami-medical-compliance-migrate:
  image: vitaminsoftware/cami-project:medical-compliance
  links:
    - 'cami-mysql'
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-migration-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
cami-medical-compliance:
  image: vitaminsoftware/cami-project:medical-compliance
  links:
    - 'cami-mysql'
    - 'cami-rabbitmq'
  ports:
    - "8000:8000"
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-medical-compliance-message-worker:
  image: vitaminsoftware/cami-project:medical-compliance
  links:
    - 'cami-mysql'
    - 'cami-rabbitmq'
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-medical-compliance-task-scheduler:
  image: vitaminsoftware/cami-project:medical-compliance
  links:
    - 'cami-mysql'
    - 'cami-rabbitmq'
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-task-scheduler-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-frontend-migrate:
  image: vitaminsoftware/cami-project:frontend
  links:
    - 'cami-mysql'
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-migration-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
cami-frontend:
  image: vitaminsoftware/cami-project:frontend
  links:
    - 'cami-mysql'
    - 'cami-rabbitmq'
  ports:
    - "8001:8001"
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-frontend-message-worker:
  image: vitaminsoftware/cami-project:frontend
  links:
    - 'cami-mysql'
    - 'cami-rabbitmq'
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-linkwatch-worker:
  image: vitaminsoftware/cami-project:linkwatch
  links:
    - 'cami-rabbitmq'
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-opentele-worker:
  image: vitaminsoftware/cami-project:opentele
  links:
    - 'cami-rabbitmq'
  entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-google-calendar:
  image: vitaminsoftware/cami-project:google-calendar
  links:
    - cami-rabbitmq
  entrypoint: docker-message-worker-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
cami-google-calendar-task-scheduler:
  image: vitaminsoftware/cami-project:google-calendar
  links:
    - cami-rabbitmq
  entrypoint: docker-task-scheduler-entrypoint.sh
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
  