# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Cami' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cami
  pod 'SwiftyJSON', '2.3.1'
  pod 'Charts', '2.2.3'

  target 'CamiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
