swagger: "2.0"
info:
  description: "Description of the CAMI Store API."
  version: "1.0.0"
  title: "CAMI Store Endpoints"
  termsOfService: "http://swagger.io/terms/"

host: <cami_hostname_or_ip>:8008
basePath: "/api/v1/"
tags:
- name: "activity"
  description: "CAMI Activity endpoint"
schemes:
- "http"
paths:
  /activity:
    post:
      tags:
      - "activity"
      summary: "Insert a new activity into the CAMI Store"
      operationId: "insertActivity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Activity object that needs to be inserted in the CAMI Store"
        required: true
        schema:
          $ref: "#/definitions/Activity"
      responses:
        200:
          description: "Activity successfully inserted"
        400:
          description: "Invalid activity content"

definitions:
  Activity:
    type: "object"
    required:
    - "event_id"
    - "user"
    - "created"
    - "updated"
    - "title"
    - "calendar_id"
    - "calendar_name"
    - "color"
    - "start"
    - "end"
    - "reminders"
    properties:
      event_id:
        type: "string"
        example: "pjm35ld41grfhrfh93472j1g24"
        
      user:
        type: "string"
        format: "URI"
        example: "/api/v1/user/2/"
        
      status:
        type: "string"
        example: "confirmed"
      
      html_link:
        type: "string"
        example: "https://www.google.com/calendar/event?eid=cGptMzVsZDQxZ3JmaHJmaDkzNDcyajFnMjQgN2VoNnFuaXZpZDY0MzBkbDc5ZWk4OWsyNmdAZw"
        
      created:
        type: "integer"
        format: "timestamp"
        example: 1494544314
        
      updated:
        type: "integer"
        format: "timestamp"
        example: 1494552610
        
      title:
        type: "string"
        example: "Tennis w/ Joel"
      
      description:
        type: "string"
        example: "Meet with Joel for playing tennis"
        
      location:
        type: "string"
        example: "Ridgeway Park"
        
      creator:
        type: "string"
        format: "json"
        example: "{u'email': u'proiect.cami@gmail.com'}"

      calendar_id:
        type: "string"
        example: "7eh6qnivid6430dl79ei89k26g@group.calendar.google.com"
        
      calendar_name:
        type: "string"
        example: "Appointments"
        
      color:
        type: "string"
        format: "json"
        example: "{u'foreground': u'#000000', u'id': u'16', u'background': u'#4986e7'}"
        
      start:
        type: "integer"
        format: "timestamp"
        example: 1494599400
        
      end:
        type: "integer"
        format: "timestamp"
        example: 1494603000
        
      recurring_event_id:
        type: "string"
        example: "h5bk4mchboa9od1uroe93nthi8"
      
      iCalUID:
        type: "string"
        example: "pjm35ld41grfhrfh93472j1g24@google.com"
        
      reminders:
        type: "string"
        format: "json"
        example: "{}"
        
      activity_type:
        type: "string"
        enum:
          - "personal"
          - "exercise"
          - "medication"
          - "measurement"
      
      
      
      
      
      
      
      
      
      
      
      
      
      