# Use a base image that has ansible set up.
FROM williamyeh/ansible:ubuntu16.04

# Add playbooks to the Docker image. This requires that the build context is the
# project root folder. Run build like:
# `docker build -f docker/cami-store/Dockerfile .`
COPY ../ /cami-project
WORKDIR /cami-project

# Run Ansible to configure the Docker image
RUN ansible-playbook ../ansible/opentele.yml -c local

COPY ../docker/opentele/docker-message-worker-entrypoint.sh /usr/local/bin/
COPY ../docker/opentele/docker-message-worker-entrypoint-dev.sh /usr/local/bin/

RUN touch /cami-project/opentele/debug.log
RUN chmod a+rw /cami-project/opentele/debug.log
RUN adduser --disabled-password --gecos '' opentele
RUN chown -R opentele /cami-project

USER opentele

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 8000
