#This is a sample Image
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive
ENV JAVA_HOME       /usr/lib/jvm/java-8-oracle
ENV LANG            en_US.UTF-8
ENV LC_ALL          en_US.UTF-8

RUN apt-get update && \
  apt-get install -y --no-install-recommends locales && \
  locale-gen en_US.UTF-8 && \
  apt-get dist-upgrade -y && \
  apt-get --purge remove openjdk* && \
  echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections && \
  echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" > /etc/apt/sources.list.d/webupd8team-java-trusty.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 && \
  apt-get update && \
  apt-get install -y --no-install-recommends oracle-java8-installer oracle-java8-set-default && \
  apt-get clean all

# Install Maven as it is needed to build the project
RUN apt-get -y install maven

# Resolve everything this project is dependent on
COPY ./smart-scheduling/pom.xml .
RUN mvn dependency:go-offline

COPY . /cami-project
WORKDIR /cami-project/smart-scheduling

COPY docker/smart-scheduling/docker-smart-scheduling-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-smart-scheduling-entrypoint.sh

# Copy the dependencies, by default to target/dependency
RUN mvn dependency:copy-dependencies

ENTRYPOINT ["docker-smart-scheduling-entrypoint.sh"]
EXPOSE 8080