# Use a base image that has ansible set up.
FROM williamyeh/ansible:ubuntu16.04

# Add playbooks to the Docker image. This requires that the build context is the
# project root folder. Run build like:
# `docker build -f docker/cami-store/Dockerfile .`
COPY . /cami-project
WORKDIR /cami-project

# Run Ansible to configure the Docker image
RUN ansible-playbook ansible/medical_compliance.yml -c local

COPY docker/cami-medical-compliance/docker-entrypoint.sh /usr/local/bin/
COPY docker/cami-medical-compliance/docker-migration-entrypoint.sh /usr/local/bin/
COPY docker/cami-medical-compliance/docker-message-worker-entrypoint.sh /usr/local/bin/
COPY docker/cami-medical-compliance/docker-message-worker-entrypoint-dev.sh /usr/local/bin/
COPY docker/cami-medical-compliance/docker-task-scheduler-entrypoint.sh /usr/local/bin/
COPY docker/cami-medical-compliance/docker-task-scheduler-entrypoint-dev.sh /usr/local/bin/

RUN touch /cami-project/medical_compliance/debug.log
RUN chmod a+rw /cami-project/medical_compliance/debug.log
RUN adduser --disabled-password --gecos '' medical_compliance
RUN chown -R medical_compliance /cami-project

USER medical_compliance

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 8000
