# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('weight', 'weight'), ('heart', 'heart'), ('sleep', 'sleep')], max_length=20)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('warning', 'warning'), ('wakeup', 'wakeup')], max_length=20)),
                ('timestamp', models.BigIntegerField()),
                ('message', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
