# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('recipient_type', models.CharField(choices=[('elderly', 'elderly'), ('caregiver', 'caregiver')], max_length=20)),
                ('type', models.CharField(choices=[('weight', 'weight'), ('heart', 'heart'), ('sleep', 'sleep')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=20)),
                ('timestamp', models.BigIntegerField()),
                ('message', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
