# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNotificationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('recipient_type', models.CharField(choices=[('elderly', 'elderly'), ('caregiver', 'caregiver')], max_length=20)),
                ('mobile_os', models.CharField(choices=[('ios', 'ios'), ('android', 'android')], max_length=20)),
                ('mobile_key', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'mobile_notification_key',
            },
        ),
    ]
