# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='timezone',
            field=models.CharField(default=b'UTC', max_length=32),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
