# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
