# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170310_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
