# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-13 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20170613_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[(b'elderly', b'elderly'), (b'caregiver', b'caregiver')], max_length=20)),
                ('type', models.CharField(choices=[(b'weight', b'weight'), (b'heart', b'heart'), (b'sleep', b'sleep')], max_length=20)),
                ('severity', models.CharField(choices=[(b'low', b'low'), (b'medium', b'medium'), (b'high', b'high')], max_length=20)),
                ('timestamp', models.BigIntegerField()),
                ('message', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit_type',
            field=models.CharField(choices=[(b'no_dim', b'No dimension'), (b'bpm', b'Beats Per Minute'), (b'kg', b'Kilogram'), (b'celsius', b'Degrees Celsius'), (b'mmhg', b'Pressure in mm Hg')], default=b'kg', max_length=8),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Measurement'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
