# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-13 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170613_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'Journal entries'},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='recipient_type',
        ),
    ]
