# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-20 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20170614_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[(b'APNS', b'Apple Push Notifications Service'), (b'GCM', b'Google Cloud Messaging'), (b'WNS', b'Windows Push Notification Services')], max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('registration_id', models.TextField()),
                ('other_info', django_mysql.models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
