# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20170802_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='gateway_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[(b'personal', b'personal'), (b'exercise', b'exercise'), (b'medication', b'medication')], default=b'personal', max_length=16),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(choices=[(b'weight', b'weight'), (b'heart', b'heart'), (b'sleep', b'sleep'), (b'exercise', b'exercise'), (b'medication', b'medication'), (b'appointment', b'appointment')], max_length=20),
        ),
    ]
