# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20170822_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_identifier',
            field=models.CharField(default=uuid.uuid4, max_length=64, null=True),
        ),
    ]
