# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    DeviceModel = apps.get_model('store', 'Device')
    for row in DeviceModel.objects.all():
        row.device_identifier = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_device_device_identifier'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
