# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20170825_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_identifier',
            field=models.CharField(default=uuid.uuid4, max_length=128, unique=True),
        ),
    ]
