# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-22 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20170913_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(choices=[(b'weight', b'Weight Measurement'), (b'blood_pressure', b'Blood Pressure Measurement'), (b'pulse', b'Heart Rate Measurement'), (b'saturation', b'Blood Oxygen Saturation Measurement'), (b'steps', b'Pedometry'), (b'sleep', b'Minutes of Sleep')], default=b'weight', max_length=32),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit_type',
            field=models.CharField(choices=[(b'no_dim', b'No dimension'), (b'bpm', b'Beats Per Minute'), (b'kg', b'Kilogram'), (b'celsius', b'Degrees Celsius'), (b'mmhg', b'Pressure in mm Hg'), (b'minutes', b'Minutes')], default=b'kg', max_length=8),
        ),
    ]
