# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-05 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20170922_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[(b'personal', b'personal'), (b'exercise', b'exercise'), (b'medication', b'medication'), (b'health-measurment', b'health-measurement')], default=b'personal', max_length=16),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(choices=[(b'weight', b'weight'), (b'heart', b'heart'), (b'steps', b'steps'), (b'sleep', b'sleep'), (b'exercise', b'exercise'), (b'medication', b'medication'), (b'appointment', b'appointment'), (b'health-measurment', b'health-measurement'), (b'fall', b'fall')], max_length=20),
        ),
    ]
