# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_auto_20180228_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalMonitoringService',
        ),
    ]
