# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-09 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_auto_20180228_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_devices', to='store.Gateway'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[(b'weight', b'Weight Scale'), (b'blood_pressure', b'Blood Pressure Monitor'), (b'pulse', b'Heart Rate Monitor'), (b'oxymeter', b'Oxymeter'), (b'pedometer', b'Step Counter'), (b'motion_sensor', b'Motion Sensor'), (b'door_window_sensor', b'Door/Window Sensor'), (b'kitchen_motion_sensor', b'Kitchen Motion Sensor'), (b'bedroom_motion_sensor', b'Bedroom Motion Sensor'), (b'bathroom_motion_sensor', b'Bathroom Motion Sensor')], default=b'weight', max_length=32),
        ),
    ]
