---
- name: Setup Medical Compliance microservice
  hosts: all
  become: yes

  roles:
    - python_setuptools
    - django

  tasks:
    - name: Install requirements
      pip:
        requirements: "{{ vagrant_project_dir}}/medical_compliance/requirements.txt"
