---
- name: Setup RabbitMQ server instance
  hosts: all

  roles:
    - rabbitmq

  tasks:
    - block:
      - name: Read rabbitmq users
        command: rabbitmqctl list_users
        register: rabbitmq_users

      - name: Create cami user
        command: rabbitmqctl add_user "{{ rabbitmq_cami_user }}" "{{ rabbitmq_cami_pass }}"
        when: rabbitmq_users.stdout.find("{{ rabbitmq_cami_user }}") == -1

      - name: Read rabbitmq vhosts
        command: rabbitmqctl list_vhosts
        register: rabbitmq_vhosts

      - block:
        - name: Add cami vhost
          command: rabbitmqctl add_vhost "{{ rabbitmq_cami_vhost }}"

        - name: Give permission to cami user on cami vhost
          command: rabbitmqctl set_permissions -p "{{ rabbitmq_cami_vhost }}" "{{ rabbitmq_cami_user }}" ".*" ".*" ".*"

        when: rabbitmq_vhosts.stdout.find("{{ rabbitmq_cami_vhost }}") == -1

      become: yes
