---
- name: Install MySQL
  hosts: all
  become: yes

  roles:
    - mysql

  tasks:
    - name: Create cami user
      mysql_user:
        name: "{{ mysql_cami_user }}"
        password: "{{ mysql_cami_pass }}"
        state: present
        priv: "*.*:ALL"
        login_user: root
        login_password: "{{ mysql_root_pass }}"

    - name: Import cami schema
      mysql_db:
        state: import
        name: all
        target: ../store/cami.sql
        login_user: "{{ mysql_cami_user }}"
        login_password: "{{ mysql_cami_pass }}"
