# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('daily_dose', models.IntegerField()),
            ],
            options={
                'db_table': 'medication_plan',
            },
        ),
    ]
