# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_medical_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithingsMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withings_user_id', models.BigIntegerField()),
                ('type', models.IntegerField(choices=[(1, 'weight'), (4, 'height'), (5, 'fat_free_mass'), (6, 'fat_ratio'), (8, 'fat_mass_weight'), (9, 'diastolic_blood_pressure'), (10, 'systolic_blood_pressure'), (11, 'heart_pulse')], default=1)),
                ('retrieval_type', models.IntegerField(choices=[(0, 'sensed_sure'), (1, 'sensed_unsure'), (2, 'manual'), (4, 'manual_creation'), (5, 'auto_blood_pressure')], default=0)),
                ('measurement_unit', models.CharField(default='kg', max_length=6)),
                ('timestamp', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('value', models.FloatField()),
            ],
        ),
    ]
