# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_withingsmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('input_source', models.CharField(choices=[('withings', 'withings')], max_length=20)),
                ('measurement_unit', models.CharField(choices=[('kg', 'kg')], max_length=2)),
                ('timestamp', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('value', models.FloatField()),
            ],
        ),
    ]
