# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weightmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('input_source', models.CharField(choices=[('google_fit', 'google_fit')], max_length=20)),
                ('measurement_unit', models.CharField(choices=[('bpm', 'bpm')], max_length=3)),
                ('timestamp', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('value', models.FloatField()),
            ],
        ),
    ]
