# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_heartratemeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepsMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('input_source', models.CharField(choices=[('google_fit', 'google_fit'), ('test', 'test')], max_length=20)),
                ('measurement_unit', models.CharField(choices=[('steps', 'steps')], max_length=5)),
                ('start_timestamp', models.BigIntegerField()),
                ('end_timestamp', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='heartratemeasurement',
            name='input_source',
            field=models.CharField(choices=[('cinch', 'cinch'), ('test', 'test')], max_length=20),
        ),
    ]
