#!/usr/bin/env python

import json
import sys

if __name__ == '__main__':
    if len(sys.argv) < 4:
        print 'Usage: ./push notification type severity message'
        sys.exit(1)

    notification = {}
    notification['type'] = sys.argv[1]
    notification['severity'] = sys.argv[2]
    notification['message'] = sys.argv[3]

    notification_json = json.dumps(notification)
    with open('notification.json', 'w') as f:
        f.write(notification_json)
